# Generated by Django 3.2.14 on 2023-08-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_assistant',
        ),
    ]
